### PR TITLE
Updated README.md's screenshot, which closes #11

### LINKED ISSUE #11: [Bug] Screenshot in README
The profile picture in the Screenshot linked in the README file is different than the current profile picture of the bot on Twitter. 

Please make the necessary changes.

### PR DESCRIPTION
**Pull request by patel-himanshu**
Also, did some trivial changes to README.md

### CODE REVIEW

**Review by jai-dewani — APPROVED** [review]
Looks good to me, 
Welcome @patel-himanshu :)

**Comment by kcoder63** [comment]
Thank you for contributing! @patel-himanshu

**Comment by kcoder63** [comment]
@all-contributors please add @patel-himanshu

**Comment by kcoder63** [comment]
@all-contributors please add @patel-himanshu  for documentation

**Pull request merged**
