### PR TITLE
Add functionality of "Replying with an image" 🎉 

### PR DESCRIPTION
**Pull request by jai-dewani**
- Created script to generate images
- Updated the code for the bot to reply with random images

### CODE REVIEW

**Comment by kcoder63** [comment]
Awesome, thank you! 🎉

**Comment by jai-dewani** [comment]
# No, You're awesome 
image

**Comment by kcoder63** [comment]
@all-contributors please add @jai-dewani for features

**Comment by kcoder63** [comment]
@all-contributors please add @jai-dewani for code

**Comment by kcoder63** [comment]
@all-contributors please add @vyvy-vi for answering questions

**Pull request merged**
